version: '3'
services:
    db:
       image: mysql:5.7
       command: --innodb-use-native-aio=0
       container_name: mysql_db
       restart: always
       tty: true
       volumes:
           - ./mysql/volume:/var/lib/mysql
       environment:
           - MYSQL_DATABASE=node_db
           - MYSQL_ROOT_PASSWORD=root
           - MYSQL_USER=rlsp
           - MYSQL_USER_PASSWORD=rlsp
       
       networks:
           - mysql-node-network

    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        image: rlatorraca/nginx_node_prod:1.0
        container_name: nginx
        networks:
            - mysql-node-network
        ports:
            - "8080:80"
    
    app:
        build:
            context: ./node
            dockerfile: Dockerfile
        container_name: node-app
        networks:
            - mysql-node-network
        volumes:
            - ./node/volume:/usr/src/app/volume
        tty: true
        entrypoint: dockerize -wait tcp://db:3306 -timeout 30s docker-entrypoint.sh
        command: node index.js
        ports:
            - "3000:3000"
    

networks:
    mysql-node-network:
        driver: bridge
